checkpoint

diff --git a/bin/pullhash b/bin/pullhash
--- a/bin/pullhash
+++ b/bin/pullhash
@@ -11,13 +11,12 @@ ENDPOINT="$MIMIS_ORIGIN"
 
 [ $# == 0 ] && {
     echo "Usage: $0 [file]+"
-    echo " Pushes the hashes for a list of files to:"
-    echo "    $MIMIS_ORIGIN"
+    echo " Pulls the hashes for a list of files to:"
     echo "    A SSH endpoint of git:~/.../"
     echo
     echo " Will call lnhash if a file is not a hash link."
     echo
-    echo " find -name ttf -print0 | xargs -0 pushhash"
+    echo " pullhash ."
     [ -n "$ENDPOINT" ] && {
         echo $'\x0A'' $ENDPOINT:'$ENDPOINT
     }
@@ -30,12 +29,10 @@ ENDPOINT="$MIMIS_ORIGIN"
 }
 
 for arg in "$@"; do
+    [ -z "$arg" ] && continue
+
     LINK="$(readlink "$arg")"
-    [[ ! -z "$LINK" && ! -e "$arg" ]] && {
-        [ -z "$VERBOSE" ] || echo "Skip Broken Link: $arg"
-        continue
-    }
-    
+
     [[ ! -z "$LINK" && ! -e "$LINK" ]] && {
         [ -z "$VERBOSE" ] || echo "Pulling: $arg"
         rsync --progress "$ENDPOINT:$LINK" "$LINK"
@@ -57,29 +54,30 @@ for arg in "$@"; do
         continue
     }
 
-    [ -d "$arg" ] && {
+    [[ -d "$arg" && $(ls -1 "$arg" | wc -l) -gt 0 ]] && {
         arg="${arg%/}/"
         [ -z "$VERBOSE" ] || echo "Descending Into: $arg"
-        pushhash "$arg"*
+        pullhash "$arg"*
         continue
     }
 
-    echo "U"
+    
+    [ -z "$REALLY_VERBOSE" ] || echo "File: $arg"
 done
 
-for arg in "$@"; do
-    LINK="$(readlink "$arg")"
+# for arg in "$@"; do
+#     LINK="$(readlink "$arg")"
 
-    ENDPOINT="$MIMIS_ORIGIN"
-    [[ ! -z "$LINK" && ! -e "$LINK" ]] && {
-        [ -z "$ENDPOINT" ] && {
-            ENDPOINT="$(git remote -v | grep -e "^origin	ssh://.* (push)$" | perl -pe 's|^origin	ssh://(.+?)/.*|\1|')"
-        }
-        [ -z "$ENDPOINT" ] && {
-            echo 'Error: No destination server found'
-            exit -1
-        }
-        echo "Pulling: $arg"
-        rsync "$ENDPOINT:$LINK" "$LINK"
-    }
-done
+#     ENDPOINT="$MIMIS_ORIGIN"
+#     [[ ! -z "$LINK" && ! -e "$LINK" ]] && {
+#         [ -z "$ENDPOINT" ] && {
+#             ENDPOINT="$(git remote -v | grep -e "^origin	ssh://.* (push)$" | perl -pe 's|^origin	ssh://(.+?)/.*|\1|')"
+#         }
+#         [ -z "$ENDPOINT" ] && {
+#             echo 'Error: No destination server found'
+#             exit -1
+#         }
+#         echo "Pulling: $arg"
+#         rsync "$ENDPOINT:$LINK" "$LINK"
+#     }
+# done
